spring.application.name=shop
spring.datasource.url=jdbc:postgresql://localhost:5434/shop
spring.datasource.username=postgres
spring.datasource.password=1waytrigger
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
jwt.secret=${JWT_SECRET}